### PR TITLE
structure_improvements

### PR DESCRIPTION
**Pull request by stefanoj3**
@evilsocket I've seen you started this nice project and thought it would be nice to make the project structure a bit more go-like

I've added a dependency manager(https://github.com/Masterminds/glide), a makefile to execute the most common tasks and also now it's just possible to go get (literally `go get github.com/evilsocket/dirsearch`) the project, so it's easier to start working on it.(check  `cmd/dirsearch/main.go` @ 20, it should be self explanatory) 

My suggestion for next commits would be to move most of the code out from the main file, and break it down in small pieces so it would become fully testable.

### CODE REVIEW

**Comment by evilsocket** [comment]
A couple of questions if you don't mind:

1. Why Glide? Shouldn't Go be already able to handle dependencies via import statements?
2. Why a Makefile?

PS: **Thanks!**

**Comment by stefanoj3** [comment]
1. Go can handle dependencies, yes, but it offers almost nothing to lock specific versions, if you simply go get you dependencies you might get different versions
(check the following link for an overview of the situation of go vendoring: http://stackoverflow.com/questions/24855081/how-do-i-import-a-specific-version-of-a-package-using-go-get)

2. No specific reason, it's a tool like many other, but everyone has make out of the box(unless you choose to use windows), so personally I usually opt for it, but of course can be replaced with anything that can do the same 😄

**Comment by evilsocket** [comment]
1. The Go philosophy is, as far as I read, to keep one version in one repo, master always points to stable, there's no need to use deps managers.

2. One of the main reason I'm switching to Go, is exactly to avoid using build tools :D

**Comment by stefanoj3** [comment]
1. True but you have no way to assert that the repo maintainer is not going to break the "stable" master, unless you lock to a specific version, and trust me, this happens more often than you can immagine! :P

2. What is wrong with build tool? I mean, at least the Makefile I added is doing pretty basic tasks, but yet stuff I would personally avoid to remember/type every time

**Comment by evilsocket** [comment]
1. Fair enough :D
2. Nothing, i just find it redundant for Go.

**Pull request merged**
